* d/t/phpunit: Don't treat patch cleanup error as fatal.     - If patch -R errors, mention it but don't count it as a testing failure.

diff --git a/debian/tests/phpunit b/debian/tests/phpunit
--- a/debian/tests/phpunit
+++ b/debian/tests/phpunit
@@ -25,6 +25,8 @@ components=$(find src/Symfony -mindepth 3 -type f -name phpunit.xml.dist -printf
 echo "$components" | parallel --gnu --keep-order 'echo -e "\\nRunning {} tests"; SYMFONY_DEPRECATIONS_HELPER=weak phpunit --colors=always --exclude-group network,tty,benchmark,intl-data,functional,composer {} || (echo -e "\\e[41mKO\\e[0m {}" && $(exit 1));' && exit_code=0 || exit_code=$?
 set -x
 
-patch -Rp1 < debian/patches/DEP-8/Tests-against-installed-classes.patch
+if ! patch -Rp1 < debian/patches/DEP-8/Tests-against-installed-classes.patch; then
+    echo "Patch failed to reverse-apply"
+fi
 
 exit $exit_code
